package experian.mobilesdk;


import android.app.NotificationManager;
import android.app.NotificationChannel;
import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.support.v4.app.NotificationCompat;
import android.support.v4.app.NotificationManagerCompat;
import android.support.v4.content.WakefulBroadcastReceiver;
import android.util.Log;

import com.google.firebase.messaging.RemoteMessage;

import org.json.JSONException;
import org.json.JSONObject;

import static android.content.Context.NOTIFICATION_SERVICE;

/**
 * This class receives Broadcast Notifications generated by notifications.
 */
public class NotificationReceiver extends BroadcastReceiver {

    //ID's used by the  notification PI in Android
    static final int NOTIFICATION_ID = 109011;
    static final String NOTIFICATION_TAG = "EMSNotification";
    static final String TAG = "EMS:NotificationReceive";

    /**
     * Received broadcast notifications
     *
     * @param context of the application
     * @param intent  received by Notification Receiver class
     */
    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d(TAG, "Received Notification");
        if (intent.getAction().equals(context.getPackageName() + EMSIntents.EMS_SHOW_NOTIFICATION)) {
            Object data = intent.getExtras().get("data");
            if (data != null) {
                RemoteMessage message = (RemoteMessage) data;
                JSONObject jData = new JSONObject(message.getData());
                displayNotification(context, jData);
            }
        } else if (intent.getAction().equals(context.getPackageName() + EMSIntents.EMS_OPEN_NOTIFICATION)) {
            EMSMobileSDK.Default().pushNotificationRegisterOpen(context, intent);
            // launch app
            try {
                Intent launchIntent = context.getPackageManager().getLaunchIntentForPackage(context.getPackageName());
                if (launchIntent == null)
                    Log.d(TAG, "Unable to find launch intent");
                launchIntent.putExtra("EMS_OPEN_FROM_NOTIFICATION", true);
                context.startActivity(launchIntent);
                Log.d(TAG, "Leaving Receiver: " + launchIntent.getClass().toString());
            } catch (Exception ex) {
                Log.d(TAG, ex.getMessage());
            }
        }
    }


    /**
     * Method to display notification
     * This method is called whenever a Push Notification comes in.
     *
     * @param context of the application
     * @param data    JSON Object received from the Broadcastreceiver
     */
    protected void displayNotification(Context context, JSONObject data) {
        String title = "";
        String body = "";
        String channelId = context.getString(R.string.default_notification_channel_id);
        String channelName = context.getString(R.string.default_notification_channel_name);


        NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(context, channelId);

        // set default icon
        mBuilder.setSmallIcon(R.drawable.notification_icon);

        //Attempts to extract the tile from the Push Notification.
        if (data.has("title")) {
            try {
                title = data.getString("title");
                mBuilder.setContentTitle(title);
            } catch (JSONException e) {
                mBuilder.setContentTitle("");
            }
        }

        //Attempts to extract the tile from the Push Notification.
        if (data.has("body")) {
            try {
                body = data.getString("body");
                mBuilder.setContentText(body);
            } catch (JSONException e) {
                mBuilder.setContentText("");
            }
        }

        Intent resultIntent;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            resultIntent = new Intent(context, NotificationReceiver.class);
            resultIntent.setAction(context.getPackageName() + EMSIntents.EMS_OPEN_NOTIFICATION);
        } else {
            resultIntent = new Intent(context.getPackageName() + EMSIntents.EMS_OPEN_NOTIFICATION);
        }

        try {
            resultIntent.putExtra("ems_open", data.getString("ems_open"));
        } catch (JSONException e) {
            e.printStackTrace();
        }

        PendingIntent resultPendingIntent = PendingIntent.getBroadcast(context, 0, resultIntent, PendingIntent.FLAG_UPDATE_CURRENT);
        mBuilder.setContentIntent(resultPendingIntent);
        mBuilder.setAutoCancel(true);
        NotificationManager mNotifyMgr = (NotificationManager) context.getSystemService(NOTIFICATION_SERVICE);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(channelId, channelName, NotificationManager.IMPORTANCE_DEFAULT);
            channel.setDescription(body);

            mNotifyMgr.createNotificationChannel(channel);
            mBuilder.setChannelId(channelId);
        }

        mNotifyMgr.notify(NOTIFICATION_TAG, NOTIFICATION_ID, mBuilder.build());
    }
}